server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    close-timeout: 15   # 在考虑结束之前等待的时间
    in-memory: true      # 默认代理URL是否应该在内存中。如果指定了显式代理，则忽略此值。
    non-blocking-redelivery: false  # 是否在回滚回滚消息之前停止消息传递。这意味着当启用此命令时，消息顺序不会被保留。
    send-timeout: 0     # 等待消息发送响应的时间。设置为0等待永远。
    queue-name: myqueue
    topic-name: mytopic
    packages:
      trust-all: true # 不配置此项，会报错
    pool:
      enabled: true
      max-connections: 10   # 连接池最大连接数
      idle-timeout: 30000   # 空闲的连接过期时间，默认为30秒
    jms:
      pub-sub-domain: true  # 默认情况下activemq提供的是queue模式，若要使用topic模式需要配置下面配置
# mybatis配置
mybatis:
  type-aliases-package: com.zwl.job.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰
logging:
  level:
    com:
      zwl:
        job:
          dao: debug
# UidGenerator
uid:
  epochStr: 2021-01-01 # 初始时间, 默认:"2019-02-20"
  timeBits: 41 # 时间位, 默认:30
  workerBits: 10 # 机器位, 默认:16
  seqBits: 12 # 序列号, 默认:7
  enableBackward: true # 是否容忍时钟回拨, 默认:true
  CachedUidGenerator:
    boostPower: 3 # RingBuffer size扩容参数, 可提高UID生成的吞吐量, 默认:3
    paddingFactor: 50 # 指定何时向RingBuffer中填充UID, 取值为百分比(0, 100), 默认为50